services:
  grafana:
    image: grafana/grafana-enterprise:10.2.3
    container_name: grafana
    restart: unless-stopped
    # if you are running as root then set it to 0
    # else find the right id with the id -u command
    user: '0'
    ports:
      - '3000:3000'
    # adding the mount volume point which we create earlier
    volumes:
      - '../data:/var/lib/grafana'
      - '../provisioning:/etc/grafana/provisioning'
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - INFLUX_USER=${INFLUX_USER}
      - INFLUX_PASSWORD=${INFLUX_PASSWORD}